# Description

+ There is a problem about the original data that some countries has negative new case or sudden drop value to 0

+ Fix and generet daily_case and store in processed

# Environment

## Library Imports

In [1]:
import os
import gc
gc.enable()

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
plt.style.use('ggplot')

from IPython.core.debugger import set_trace

## Local Imports

In [2]:
from phuc import data_process, file
from phuc import visualization as vs

In [3]:
def average_over_group(series, ix, number_of_average):
    
    delta_ix = int(number_of_average/2) 
#     set_trace()
    try:
        if (ix + delta_ix >= len(series)):
            raise IndexError('Out Of range')
            
        sum_local = series[ix-delta_ix:ix+delta_ix+1].sum()

        propose_value = int(sum_local/number_of_average)
        
        series[ix-delta_ix:ix+delta_ix] = propose_value

        series[ix+delta_ix] = \
               sum_local - (number_of_average - 1)*propose_value
        
    except IndexError:
        
        # Fix finitive loop due to the last row is negative:
        condition = series[ix] > -3 and -2 <= series[ix-1] and series[ix]<2
        if (condition):
            series[ix] =0;
        
        # move index backward to avoid Out Of range
        average_over_group(series, ix-1, number_of_average)

In [4]:
def smoth_drop_zero(series, ix, number_of_average, drop_limit):
    
    condition_left = False
    
    delta_ix = int(number_of_average/2)
        
    condition_left = series[ \
              ix-delta_ix:ix+delta_ix].sum() > drop_limit
    if (ix + delta_ix >= len(series)):
            condition_right = False
            pass
    else:
        condition_right = series[ \
              ix:ix+delta_ix+1].sum() > drop_limit

    if (condition_right or condition_left):
        average_over_group(series, ix, number_of_average)

In [5]:
def get_new_daily_case(df, nation):
    new_case = df[nation][1:].reset_index(drop=True)
    old_case = df[nation][0:-1].reset_index(drop=True)
    
    new_daily_case = new_case - old_case
    
    return new_daily_case

In [6]:
def remove_below_zero(series, number_of_average):
    
    ix_below_zero = np.where(series < 0)[0]

    while (len(ix_below_zero) > 0):

        for ix in ix_below_zero:
            average_over_group(series, ix, number_of_average)

        ix_below_zero = np.where(series < 0)[0]

In [7]:
def remove_sudden_drop_zero(series,drop_limit, number_of_average):
    
    ix_equal_zero = np.where(new_daily_case[nation] == 0)[0]

    for ix in ix_equal_zero:
        smoth_drop_zero(new_daily_case[nation], ix, \
                        number_of_average ,drop_limit)

## Reload data path

In [8]:
from phuc.file import standard_template

standard_template.save_data_path(os.getcwd().split('/src')[0])

Loaded file data_path.pkl
Directory  /home/phuc/Desktop/Work/Data Sience/Epidemic Modeling/MathModel  already exists
Saved file data_path.pkl

##  Setup Pandas

In [9]:
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 100)

pd.options.mode.chained_assignment = None

## Set up data path

In [10]:
CURR_DIR = os.getcwd().split('/src')[0]

In [11]:
dir_path = file.load_pickle(CURR_DIR + '/data_path.pkl')['DIRS']
file_path = file.load_pickle(CURR_DIR + '/data_path.pkl')['FILES']

Loaded file data_path.pkl
Loaded file data_path.pkl

# Code

## Load Data

In [12]:
confirmed = file.load_pickle(file_path['WORKING_CONFIRMED_PKL_PATH'])

recovered = file.load_pickle(file_path['WORKING_RECOVERED_PKL_PATH'])

death = file.load_pickle(file_path['WORKING_DEATH_PKL_PATH'])

Loaded file working_confirmed.pkl
Loaded file working_recovered.pkl
Loaded file working_death.pkl

## Calculate new case daily

For some unknown reasons, The newly case update fall below 0, which does not make any sense.

In [13]:
for df_name, df in [['daily_confirmed', confirmed],
                    ['daily_recovered', recovered],
                    ['daily_death', death]]:

    nations = df.columns[1:]
    
    new_daily_case = df[['Date']][:-1]

    for nation in nations:

        new_daily_case[nation] = get_new_daily_case(df, nation)
        
    ix_below_zero = np.where(new_daily_case[nations] < 0)[0]
    
    print (df_name)
    
    display(new_daily_case.iloc[ix_below_zero])

daily_confirmed

,Date,Austria,Belgium,Bulgaria,Czechia,Denmark,Finland,France,Germany,Ireland,Italy,Poland,Portugal,Romania,Spain
86,2020-04-17,76,1045,32,57,169,192,-17,1945,778,3491,363,663,351,887
90,2020-04-21,52,933,49,99,217,115,-2206,2357,631,3370,313,603,468,4211
92,2020-04-23,69,1496,137,86,137,111,1610,1870,577,3021,381,444,321,-10034
97,2020-04-28,45,525,48,75,157,166,-2512,1627,376,2086,422,183,362,2144
100,2020-05-01,27,485,39,18,96,125,1212,890,343,1900,270,-161,165,1366
111,2020-05-12,36,202,46,48,76,51,-226,927,159,888,283,219,224,661
114,2020-05-15,92,345,37,49,67,58,-112,519,92,875,241,227,267,515
122,2020-05-23,17,282,19,65,71,11,-105,342,57,531,395,152,213,482
123,2020-05-24,36,250,6,47,27,20,307,272,59,300,305,165,213,-372
124,2020-05-25,18,113,10,48,41,29,-279,600,37,397,443,219,146,859
131,2020-06-01,26,98,19,62,35,2,-840,285,4,318,230,195,119,294
148,2020-06-18,48,128,81,126,47,14,569,482,13,-148,301,375,320,307
153,2020-06-23,41,88,128,127,54,12,-187,391,5,577,294,367,321,334
154,2020-06-24,28,109,166,93,21,5,-255,500,9,296,298,311,460,400
156,2020-06-26,58,103,112,260,0,7,-194,422,23,175,319,323,325,564
157,2020-06-27,74,86,66,305,0,0,-723,235,2,174,193,457,291,301
163,2020-07-03,115,111,180,121,0,6,-358,418,11,235,314,413,416,0
164,2020-07-04,115,178,63,75,0,5,-11,325,18,192,231,328,391,0
167,2020-07-07,92,65,240,129,12,3,-293,356,4,193,277,443,555,383

daily_recovered

,Date,Austria,Belgium,Bulgaria,Czechia,Denmark,Finland,France,Germany,Ireland,Italy,Poland,Portugal,Romania,Spain
32,2020-02-23,0,0,0,0,0,0,0,0,0,-1,0,0,0,0
54,2020-03-16,-5,0,0,0,0,0,0,0,5,192,0,0,7,498
56,2020-03-18,0,0,0,0,0,0,0,8,0,415,-12,0,6,26
57,2020-03-19,0,-30,0,1,0,0,0,67,0,0,0,2,0,481
114,2020-05-15,53,159,28,41,148,0,-1,1003,0,2605,257,494,204,1663
118,2020-05-19,204,160,38,104,120,-200,467,1285,1590,2881,280,21,190,0
130,2020-05-31,3,32,16,84,50,0,-3,280,0,848,178,143,170,0
144,2020-06-14,7,21,54,70,22,0,-101,603,0,640,157,183,98,0
156,2020-06-26,23,23,18,14,0,0,-95,369,0,969,754,231,349,0
163,2020-07-03,49,18,6,4,0,0,-89,700,0,477,476,348,309,0
167,2020-07-07,35,16,129,100,18,100,-230,492,0,825,640,269,265,0

daily_death

,Date,Austria,Belgium,Bulgaria,Czechia,Denmark,Finland,France,Germany,Ireland,Italy,Poland,Portugal,Romania,Spain
74,2020-04-05,16,185,2,11,8,-1,833,226,16,636,13,16,25,700
79,2020-04-10,18,327,3,10,13,1,635,-31,33,619,27,35,21,525
110,2020-05-11,3,54,2,1,-6,4,347,77,21,172,28,19,20,176
114,2020-05-15,1,46,3,1,6,4,-2,41,15,153,8,13,24,104
116,2020-05-17,0,28,2,-1,1,2,131,41,4,99,11,13,13,146
117,2020-05-18,3,28,2,5,3,1,-217,78,14,162,12,16,17,69
123,2020-05-24,1,32,0,2,1,1,90,26,-2,92,11,14,20,-1918
123,2020-05-24,1,32,0,2,1,1,90,26,-2,92,11,14,20,-1918
130,2020-05-31,0,19,0,1,2,-2,28,15,-2,60,10,14,10,0
130,2020-05-31,0,19,0,1,2,-2,28,15,-2,60,10,14,10,0
140,2020-06-10,1,7,1,-2,0,1,27,20,8,53,9,7,9,0
142,2020-06-12,2,4,0,-1,3,0,24,10,0,78,15,7,14,0
153,2020-06-23,0,9,1,4,0,0,9,14,6,-31,21,3,16,2
156,2020-06-26,2,1,1,0,0,0,-1,3,4,8,6,6,10,3
157,2020-06-27,2,0,3,-1,0,0,0,0,1,22,3,3,23,2
163,2020-07-03,0,6,2,-2,0,0,0,10,1,21,5,7,23,0
164,2020-07-04,1,0,5,-3,0,0,1,3,0,7,5,9,19,0
165,2020-07-05,0,3,4,2,1,0,23,-1,0,8,4,6,18,3
167,2020-07-07,0,2,5,0,0,0,-1,14,-4,15,14,2,18,4
167,2020-07-07,0,2,5,0,0,0,-1,14,-4,15,14,2,18,4

## Fix and Save daily_case + Cumulative case

In [22]:
for df_name, df in [['daily_confirmed', confirmed],
                    ['daily_recovered', recovered],
                    ['daily_death', death]]:

    nations = df.columns[1:]
    
    new_daily_case = df[['Date']][:-1]

    for nation in nations: # column based series
        
        # Calculate new daily_case
        new_daily_case[nation] = get_new_daily_case(df, nation)
        
        # Engineer below_zero and sudden_drop_zero Error by 
        # smoothing average of 3
        # drop limit is : 50

        remove_below_zero(new_daily_case[nation],
                          number_of_average = 3)

        remove_sudden_drop_zero(new_daily_case[nation], 
                                drop_limit = 50, 
                                number_of_average = 3)
        
    # Save Daily_Case:
    file.save_pickle(dir_path['PROCESSED_DIR'] +'/'+
                     df_name + '.pkl', new_daily_case)
    
    new_daily_case.to_csv(dir_path['PROCESSED_DIR'] +'/'+
                     df_name + '.csv', index = False)
    
    # Calculate Cumulative Case
    
    cumumlative_case = new_daily_case.iloc[:,1:].cumsum()
    
    cumumlative_case.reset_index(inplace = True)
    
    cumumlative_case['index'] = new_daily_case['Date']
    
    # Save Cumulative Case
    file.save_pickle(dir_path['PROCESSED_DIR'] +'/cumumlative' +
                     df_name + '.pkl', cumumlative_case)
    
    cumumlative_case.to_csv(dir_path['PROCESSED_DIR'] +'/cumumlative'+
                     df_name + '.csv', index = False)

Directory  /home/phuc/Desktop/Work/Data Sience/Epidemic Modeling/MathModel/data/processed  already exists
Saved file daily_confirmed.pkl
Directory  /home/phuc/Desktop/Work/Data Sience/Epidemic Modeling/MathModel/data/processed  already exists
Saved file cumumlativedaily_confirmed.pkl
Directory  /home/phuc/Desktop/Work/Data Sience/Epidemic Modeling/MathModel/data/processed  already exists
Saved file daily_recovered.pkl
Directory  /home/phuc/Desktop/Work/Data Sience/Epidemic Modeling/MathModel/data/processed  already exists
Saved file cumumlativedaily_recovered.pkl
Directory  /home/phuc/Desktop/Work/Data Sience/Epidemic Modeling/MathModel/data/processed  already exists
Saved file daily_death.pkl
Directory  /home/phuc/Desktop/Work/Data Sience/Epidemic Modeling/MathModel/data/processed  already exists
Saved file cumumlativedaily_death.pkl

# Colab Settings

## Connect Drive

In [ ]:
from google.colab import drive 
# conncent phuc.phan1012000@hcmut.edu.vn

# default location for the drive
ROOT = "/content/drive"            
drive.mount(ROOT)

## Load Library

In [ ]:
import sys
import os
# Load my phuc's library
sys.path.append("/content/drive/My Drive/Work/Data_Science_Library")

## Setup Project

In [ ]:
GIT_REPOSITORY = "kalapa-s-CreditScore"
# path to project on Google Drive
MY_GOOGLE_DRIVE_PATH = 'My Drive/Work/Projects'
PROJECT_PATH = os.path.join(ROOT, MY_GOOGLE_DRIVE_PATH,GIT_REPOSITORY)

# GO TO WORKING PROJECT PATH
os.chdir(PROJECT_PATH+'/src')
os.remove(PROJECT_PATH+'/data_path.pkl')